### ISSUE TITLE
Atualização

### ISSUE THREAD

**Issue by VZiemer** [renatoargh/webdanfe#1]
Olá. achei seu projeto bastante interessante, estou criando um emissor de NFe com NodeJS e gostaria de utilizá-lo como base para montar a NF e depois de autorizada imprimir a danfe.

**Comment by renatoargh** [comment]
Fala @VZiemer beleza? Valeu por achar o projeto interessante, mas não estou mais dando manutenção ativa nele. Este projeto é apenas um wraper para o site [webdanfe](https://www.webdanfe.com.br/danfe/index.html). [Eu tentei fazer a geração de DANFE em pdf](https://www.webdanfe.com.br/danfe/index.html) mas abandonei o projeto e acabei usando o [nfephp](https://github.com/nfephp-org/nfephp) que agora está descontinuado. Você pode até usar este projeto como base, mas você estará nas mãos do WebDanfe. Se eles começarem a cobrar para gerar as danfes, por exemplo, você vai ter problemas.
